max_obstacle_height: 2.0
obstacle_range: 10.0
raytrace_range: 15.0

# Box robot
footprint: [[2.45, -1], [2.45, 1], [-0.45, 1], [-0.45, -1]]

# footprint: [[1.400, -1.0], [1.400, 1], [-1.400, 1.0], [-1.400, -1]]

publish_frequency: 1.0


obstacle_layer:
#  observation_sources: scan2d # scan3d 
#  scan2d:
#    data_type: LaserScan
#    topic: front_laser/scan
#    marking: true
#    clearing: true
#    inf_is_valid: false
#    min_obstacle_height: 0.1
  observation_sources: scan3d
  scan3d:
    data_type: PointCloud2
    topic: /robot/lidar_3d/align_points
    marking: true
    clearing: true
    inf_is_valid: false
    min_obstacle_height: 1.0

