global_costmap:
  global_frame: world
  robot_base_frame: robot_base_footprint

  update_frequency: 5.0
  publish_frequency: 1.0
  transform_tolerance: 1
  always_send_full_costmap: true

  width:  2000.0
  height: 2000.0
  resolution: 0.5
  origin_x: -1000.0
  origin_y: -1000.0

  publish_voxel_map: true
  
  static_map: true
  rolling_window: false
  
  plugins:
    # - name: voxel_layer
    #   type: "costmap_2d::VoxelLayer"
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  obstacle_layer:
    enabled: true

  inflation_layer:
    enabled: true
    cost_scaling_factor: 1.0 # the lower, the more cost
    inflation_radius: 0.01 # big values make it harder to pass through narrow spaces
  
