local_costmap:
  global_frame: robot_odom
  robot_base_frame: robot_base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 20.0 #5
  height: 20.0 #5
  resolution: 0.2 #0.05
  min_obstacle_height: 0.0

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"

  obstacle_layer:
    enabled: true

